#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci(max):
	list = [1,2]
	e = 0
	while list[-1] < max:
		list.append(list[e]+list[e+1])
		e = e + 1
	return list

def sum_even(list):
	result = 0
	for entry in list:
		if entry % 2 == 0:
			result = result + entry
	return result

print sum_even(fibonacci(4000000))